dependencies:
  flutter:
    sdk: flutter

  provider:

dev_dependencies:
  flutter_lints:

  flutter_test:
    sdk: flutter

environment:
  sdk: ^3.1.0

flutter:
  uses-material-design: true

name: ChessyMess

publish_to: none
