dependencies:
  flutter:
    sdk: flutter

  provider:

  fast_immutable_collections:

  flutter_svg:

dev_dependencies:
  flutter_lints:

  flutter_test:
    sdk: flutter

environment:
  sdk: ^3.1.0

flutter:
  assets:
    - assets/

  uses-material-design: true

name: chessy_mess

publish_to: none
